### ISSUE TITLE
Update axios in package.json

### ISSUE THREAD

**Issue by gmuehl** [nachodd/vue-auth-href#11]
Upgrade the Version of axios in package.json, node reports

> found 1 high severity vulnerability
>   run `npm audit fix` to fix them, or `npm audit` for details

details:

>  High            Server-Side Request Forgery                                   
>   Package         axios                                                         
>   Patched in      >=0.21.1                                                      
>   Dependency of   vue-auth-href                                                 
>   Path            vue-auth-href > axios                                         
>   More info       https://npmjs.com/advisories/1594

**Comment by nachodd** [comment]
Done! and I updated the package to v1.1.1 💪 
Thanks!
