### ISSUE TITLE
version 1.3.0

### ISSUE THREAD

**Issue by shikamu** [nachodd/vue-auth-href#17]
Hello,
I've been waiting for a month now that version 1.3.0 with my latest pull request https://github.com/nachodd/vue-auth-href/pull/16 but the version is still not released, can someone make it?

**Comment by nachodd** [comment]
Yeah, sorry about that. I been quite busy! 
[Here is the 1.3 version!](https://www.npmjs.com/package/vue-auth-href)
Thanks you so much for the collaboration @shikamu!
